### PR TITLE
fix compilation arm64

### PR DESCRIPTION
**Pull request by Edouard2laire**
Fix the following compilation error on arm64

```
/Users/edelaire1/Documents/software/iso2mesh/tools/meshfix/contrib/JMeshLib/include/clusterGraph.h:57:50: error: cast from pointer to smaller type 'j_voidint' (aka 'int') loses information
 clusterEdge *getFirst() {return (numels)?(edges[(j_voidint)getHead()]):(NULL);} 

```

Solution recomended here: https://stackoverflow.com/questions/22419063/error-cast-from-pointer-to-smaller-type-int-loses-information-in-eaglview-mm/22474752#22474752

### CODE REVIEW

**Comment by fangq** [comment]
thanks for the patch - meshfix is not my code, so I don't know if this change has any side effect.

after you compile this, do the examples where 'meshfix' is used still work? you can grep under iso2mesh/samples to find those, for example

https://github.com/fangq/iso2mesh/blob/master/sample/demo_merge_surfaces.m#L32

brain2mesh also uses meshfix.

**Comment by Edouard2laire** [comment]
I am not yet able to fully compile mesh fix due to [OpenNL3.2.1](https://github.com/fangq/meshfix/tree/master/contrib/OpenNL3.2.1) : https://github.com/xiaoyeli/superlu/issues/136 

edit: solved :)

**Comment by Edouard2laire** [comment]
is this error important : 

```
[ 83%] Building CXX object CMakeFiles/tet.dir/predicates.cxx.o
[100%] Linking CXX static library libtet.a
[100%] Built target tet
cp: cgalmesh/mesh_3D_image: No such file or directory
make: *** [copybin] Error 1
```

**Comment by Edouard2laire** [comment]
closing as iso2mesh is now compiled for ARM

**Pull request closed without merging**
